import Head from "next/head";
import Login from "./login";
import { UserContext } from "@/store/user-context";
import { Fragment, useContext, useEffect } from "react";
import { Button, Typography } from "@mui/material";
import { useRouter } from "next/router";
import PageTransition from "@/components/UI/PageTransition";
import { AnimatePresence, motion } from "framer-motion";

export default function Home() {
  const router = useRouter();
  const userCtx = useContext(UserContext);

  // useEffect(() => {
  //   if (!userCtx.loggedIn) {
  //     router.push("/login");
  //   }
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {!userCtx.isLoading && (
        <AnimatePresence mode="wait">
          {userCtx.loggedIn ? (
            <motion.div
              key='in'
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.1 }}
            >
              <Typography>
                You are logged in as {userCtx.user?.email}
              </Typography>
              <Button onClick={userCtx.signOut}>Sign out</Button>
            </motion.div>
          ) : (
            <motion.div
              key='out'
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.1 }}
            >
              <Login />
            </motion.div>
          )}
        </AnimatePresence>
      )}
    </>
  );
}
